# Generated by Django 4.0.8 on 2023-02-20 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0016_alter_story_created_by_alter_story_modified_by_and_more'),
        ('storyextras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storybookmark',
            options={'verbose_name': 'Story bookmark', 'verbose_name_plural': 'Story bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='storyrating',
            options={'verbose_name': 'Story rating', 'verbose_name_plural': 'Story ratings'},
        ),
        migrations.CreateModel(
            name='StorySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_points', models.PositiveSmallIntegerField(default=0, verbose_name='Reward points')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stories.story', verbose_name='Story')),
            ],
            options={
                'verbose_name': 'Story settings',
                'verbose_name_plural': 'Story settings',
            },
        ),
        migrations.CreateModel(
            name='StoryReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Points')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story', verbose_name='Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Story reward',
                'verbose_name_plural': 'Story rewards',
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story', verbose_name='Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Story read',
                'verbose_name_plural': 'Story reads',
                'unique_together': {('story', 'user')},
            },
        ),
    ]
