# Generated by Django 4.0.8 on 2023-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyextras', '0002_alter_storybookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysettings',
            name='cached_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='storysettings',
            name='display_rating',
            field=models.BooleanField(default=True, help_text='Display or hide the user rating for this story', verbose_name='Display the user rating'),
        ),
        migrations.AlterField(
            model_name='storysettings',
            name='reward_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many points does an user earn for reading this story', verbose_name='Reward points'),
        ),
    ]
