# Generated by Django 4.0.8 on 2023-03-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyextras', '0003_storysettings_cached_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storysettings',
            name='cached_rating',
        ),
        migrations.AddField(
            model_name='storysettings',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Average rating'),
        ),
    ]
