# Generated by Django 4.0.8 on 2023-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyextras', '0004_remove_storysettings_cached_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyreward',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many points will be awarded to the reader', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='storysettings',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Cached computed rating average', max_digits=5, verbose_name='Average rating'),
        ),
    ]
