# Generated by Django 4.0.8 on 2023-03-09 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyextras', '0005_alter_storyreward_points_alter_storysettings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyreward',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many points will be awarded to the reader', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Points'),
        ),
    ]
