# Generated by Django 4.0.8 on 2023-02-20 09:43

import dash.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0030_alter_invitation_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0010_alter_category_created_by_alter_category_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(help_text='The badge icon file', upload_to=functools.partial(dash.utils.generate_file_path, *('userbadges',), **{}), verbose_name='Image')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Short description')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='Display this item')),
                ('item_type', models.CharField(choices=[('S', 'Stories'), ('P', 'Polls')], default='S', help_text='Badge validation applies to Stories or Polls', max_length=1, verbose_name='Validation item type')),
                ('item_count', models.PositiveSmallIntegerField(default=10000, help_text='Offer this badge to users who completed this number of items', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Validation item count')),
                ('item_category', models.ForeignKey(blank=True, help_text='Restrict badge validation to a specific category', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='Validation item category')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Badge type',
                'verbose_name_plural': 'Badge types',
                'unique_together': {('org', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_on', models.DateTimeField(auto_now_add=True, verbose_name='Date offered')),
                ('accepted_on', models.DateTimeField(blank=True, null=True, verbose_name='Date accepted')),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbadges.badgetype', verbose_name='Badge type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User badge',
                'verbose_name_plural': 'User badges',
                'unique_together': {('badge_type', 'user')},
            },
        ),
    ]
