# Generated by Django 4.0.8 on 2023-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbadges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='declined_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date declined'),
        ),
    ]
