# Generated by Django 4.0.8 on 2023-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbadges', '0002_userbadge_declined_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='accepted_on',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='declined_on',
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='offered_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date offered'),
        ),
    ]
