# Generated by Django 4.0.8 on 2023-03-09 13:53

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_alter_userprofile_options_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_retries',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, help_text='How many attempts were made for this confirmation code', verbose_name='Confirmation code retries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, help_text='Cached computed total points', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='The profile image file to use', null=True, upload_to=functools.partial(dash.utils.generate_file_path, *('userprofiles',), **{}), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_code',
            field=models.CharField(blank=True, default='', editable=False, help_text='Confirmation code for the password reset', max_length=8, verbose_name='Confirmation code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_expiry',
            field=models.DateTimeField(blank=True, editable=False, help_text='Expiration date for the password reset code', null=True, verbose_name='Expiration date'),
        ),
    ]
